;;; d-constants.el --- General Daselt constants. module              -*- lexical-binding: t; -*-

;; Copyright (C) 2023  Alexander Prähauser

;; Author: Alexander Prähauser <ahprae@protonmail.com>
;; Keywords: tools
;; Version: 0.8

;; This file is part of Daselt.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;;  d constants.

;;; Code:
(declare-function d--standard-file-p (filepath) )
(defconst d-modifiers-list
  (list ?C ?H ?M ?S ?s ?A)
  "List of modifiers in their standard order in Daselt.")

(defconst d-discrete-modifiers-list
  (list ?M ?s ?A)
  "List of discrete modifiers in their standard order in Daselt.")

(defconst d-escape-kbd-regexps-list
  `(,(rx (group ",")) ,(rx (group ".")) ,(rx (group (syntax string-quote))))
  "List of character strings that should be escaped.
Used by functions like `d--generate-key-strings-from-marked-bindlist'")

(defconst d-pkg-type-modifiers-list
  '("user-defined" "special" "eval")
  "Type modifiers that files in D-EMACS/pkg-configs can have.")

(require 'd-emacs-customs)
(require 'd-functions)

(defconst d-pkg-file-types-list
  (cl-remove-duplicates
   (flatten-list
    (d-recurse-through-directory (concat d-emacs-directory "pkg-configs/")
                                 `(((lambda (filepath) (let* ((filename (file-name-base filepath))
                                                         (type (last (split-string filename
                                                                                   "-"))))
                                                    type))
                                    . (lambda (idx lst) (let ((elt (nth idx lst)))
                                                     (and (d--standard-file-p elt)
                                                          (not (file-directory-p elt)))))))))
   :test #'string=)
  "The file types appearing in D-EMACS-DIRECTORY/pkg-configs.
This constant is automatically generated by recursing through that directory.
The last part of the name of all found standard non-directory files counts as a
type. Splitting is done along -'s.")

(provide 'd-constants)
;;; d-constants.el ends here
